# ML Zoomcamp 2025: Homework of module 3. Machine Learning for Classification

In [2]:
import pandas as pd
import numpy as np

## EDA

In [3]:
df = pd.read_csv('course_lead_scoring.csv')

In [10]:
df.dtypes

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [5]:
df.describe()

number_of_courses_viewed  annual_income  interaction_count  \
count               1462.000000    1281.000000        1462.000000   
mean                   2.031464   59886.273224           2.976744   
std                    1.449717   15070.140389           1.681564   
min                    0.000000   13929.000000           0.000000   
25%                    1.000000   49698.000000           2.000000   
50%                    2.000000   60148.000000           3.000000   
75%                    3.000000   69639.000000           4.000000   
max                    9.000000  109899.000000          11.000000   

        lead_score    converted  
count  1462.000000  1462.000000  
mean      0.506108     0.619015  
std       0.288465     0.485795  
min       0.000000     0.000000  
25%       0.262500     0.000000  
50%       0.510000     1.000000  
75%       0.750000     1.000000  
max       1.000000     1.000000

In [7]:
df.head(10)

lead_source       industry  number_of_courses_viewed  annual_income  \
0      paid_ads            NaN                         1        79450.0   
1  social_media         retail                         1        46992.0   
2        events     healthcare                         5        78796.0   
3      paid_ads         retail                         2        83843.0   
4      referral      education                         3        85012.0   
5        events  manufacturing                         1        59904.0   
6  social_media     technology                         0        51283.0   
7  social_media            NaN                         5        62975.0   
8      referral     healthcare                         4        38648.0   
9      paid_ads          other                         3        59866.0   

  employment_status       location  interaction_count  lead_score  converted  
0        unemployed  south_america                  4        0.94          1  
1          employed  south_america                  1        0.80          0  
2        unemployed      australia                  3        0.69          1  
3               NaN      australia                  1        0.87          0  
4     self_employed         europe                  3        0.62          1  
5               NaN         africa                  6        0.83          1  
6               NaN    middle_east                  2        0.57          0  
7           student         europe                  4        0.62          1  
8        unemployed  south_america                  2        0.86          1  
9           student      australia                  3        0.43          1

In [8]:
for col in df.columns:
    print(col)
    print(df[col].unique()[:5])
    print(df[col].nunique())
    print()

lead_source
['paid_ads' 'social_media' 'events' 'referral' 'organic_search']
5

industry
[nan 'retail' 'healthcare' 'education' 'manufacturing']
7

number_of_courses_viewed
[1 5 2 3 0]
10

annual_income
[79450. 46992. 78796. 83843. 85012.]
1267

employment_status
['unemployed' 'employed' nan 'self_employed' 'student']
4

location
['south_america' 'australia' 'europe' 'africa' 'middle_east']
7

interaction_count
[4 1 3 6 2]
12

lead_score
[0.94 0.8  0.69 0.87 0.62]
101

converted
[1 0]
2



In [14]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

print(df.dtypes)

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
print("Categorical columns: ", categorical_columns)

numerical = ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']
print("Numerical columns: ", numerical)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(' ', '_')
        
df.head().T

lead_source                  object
industry                     object
number_of_courses_viewed      int64
annual_income               float64
employment_status            object
location                     object
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object
Categorical columns:  ['lead_source', 'industry', 'employment_status', 'location']
Numerical columns:  ['number_of_courses_viewed', 'annual_income', 'interaction_count', 'lead_score']


0              1           2          3  \
lead_source                    paid_ads   social_media      events   paid_ads   
industry                            NaN         retail  healthcare     retail   
number_of_courses_viewed              1              1           5          2   
annual_income                   79450.0        46992.0     78796.0    83843.0   
employment_status            unemployed       employed  unemployed        NaN   
location                  south_america  south_america   australia  australia   
interaction_count                     4              1           3          1   
lead_score                         0.94            0.8        0.69       0.87   
converted                             1              0           1          0   

                                      4  
lead_source                    referral  
industry                      education  
number_of_courses_viewed              3  
annual_income                   85012.0  
employment_status         self_employed  
location                         europe  
interaction_count                     3  
lead_score                         0.62  
converted                             1

In [19]:
print("\nBefore: \n",df.isnull().any())

# Check for missing values and handle them
for col in categorical_columns:
    df[col] = df[col].fillna('NA')

for col in numerical:
    df[col] = df[col].fillna(0.0)
    
print("\nAfter: \n",df.isnull().any())


Before: 
 lead_source                 False
industry                    False
number_of_courses_viewed    False
annual_income               False
employment_status           False
location                    False
interaction_count           False
lead_score                  False
converted                   False
dtype: bool

After: 
 lead_source                 False
industry                    False
number_of_courses_viewed    False
annual_income               False
employment_status           False
location                    False
interaction_count           False
lead_score                  False
converted                   False
dtype: bool


### Question 1

In [20]:
df['industry'].mode()

0    retail
Name: industry, dtype: object

### Question 2

Create the [correlation matrix](https://www.google.com/search?q=correlation+matrix) for the numerical features of your dataset.
In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- `interaction_count` and `lead_score`
- `number_of_courses_viewed` and `lead_score`
- `number_of_courses_viewed` and `interaction_count`
- `annual_income` and `interaction_count`

Only consider the pairs above when answering this question.

### Split the data

- Split your data in train/val/test sets with 60%/20%/20% distribution.
- Use Scikit-Learn for that (the `train_test_split` function) and set the seed to `42`.
- Make sure that the target value `converted` is not in your dataframe.

In [37]:
from sklearn.model_selection import train_test_split
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)
len(df_train), len(df_val), len(df_test)


(876, 293, 293)

In [38]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [39]:
y_train = df_train.converted.values
y_val = df_val.converted.values
y_test = df_test.converted.values

del df_train['converted']
del df_val['converted']
del df_test['converted']

In [45]:
df_full_train = df_full_train.reset_index(drop=True)
df_full_train.isnull().sum()

lead_source                 0
industry                    0
number_of_courses_viewed    0
annual_income               0
employment_status           0
location                    0
interaction_count           0
lead_score                  0
converted                   0
dtype: int64

In [47]:
df_full_train.converted.value_counts(normalize=True)


converted
1    0.607357
0    0.392643
Name: proportion, dtype: float64

In [48]:
df_full_train.converted.mean()

np.float64(0.6073567151411463)

In [50]:
df_full_train[categorical_columns].nunique()


lead_source          6
industry             8
employment_status    5
location             8
dtype: int64

In [54]:
corr_results = {}
for col in numerical:
    corr_results[col] = df_full_train[numerical].corrwith(df_full_train[col])

corr_matrix_corrwith = pd.DataFrame(corr_results)
print(corr_matrix_corrwith)

pairs = [
    ('interaction_count', 'lead_score'),
    ('number_of_courses_viewed', 'lead_score'),
    ('number_of_courses_viewed', 'interaction_count'),
    ('annual_income', 'interaction_count')
]

max_corr = 0
best_pair = None
for pair in pairs:
    corr = abs(corr_matrix_corrwith.loc[pair[0], pair[1]])
    if corr > max_corr:
        max_corr = corr
        best_pair = pair

print(f"\nFeatures with the biggest correlation {best_pair[0]} and {best_pair[1]} with correlation {corr_matrix_corrwith.loc[best_pair[0], best_pair[1]]:.3f}")

                          number_of_courses_viewed  annual_income  \
number_of_courses_viewed                  1.000000       0.012227   
annual_income                             0.012227       1.000000   
interaction_count                        -0.044381       0.011959   
lead_score                                0.009427       0.021273   

                          interaction_count  lead_score  
number_of_courses_viewed          -0.044381    0.009427  
annual_income                      0.011959    0.021273  
interaction_count                  1.000000    0.025393  
lead_score                         0.025393    1.000000  

Features with the biggest correlation number_of_courses_viewed and interaction_count with correlation -0.044


### Question 3
Calculate the mutual information score between `converted` and other **categorical variables** in the dataset. Use the training set only.

Round the scores to 2 decimals using round(score, 2).

In [58]:
from sklearn.metrics import mutual_info_score

mi_scores = {}

for col in categorical_columns:
    mi_score = mutual_info_score(df_full_train['converted'], df_full_train[col])
    mi_scores[col] = round(mi_score, 2)

for col, score in mi_scores.items():
    print(f"{col}: {score}")

lead_source: 0.03
industry: 0.01
employment_status: 0.01
location: 0.0


### Question 4

- Now let's train a logistic regression.
- Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
- Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
  - `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

- 0.64
- 0.74
- 0.84
- 0.94

In [ ]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LogisticRegression

dv = DictVectorizer(sparse=False)
train_dict = df_train[categorical_columns + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

# train the model
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# get predictions
y_pred = model.predict_proba(X_val)[:, 1]
convert_decision = (y_pred >= 0.5)

# calculate accuracy
accuracy = (y_val == convert_decision).mean()
print(f"Accuracy: {round(accuracy, 2)}")

Accuracy: 0.7


### Question 5

- Let's find the least useful feature using the _feature elimination_ technique.
- Train a model using the same features and parameters as in Q4 (without rounding).
- Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
- For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?

- `'industry'`
- `'employment_status'`
- `'lead_score'`

> **Note**: The difference doesn't have to be positive.


In [ ]:
# Original features
features = categorical_columns + numerical

dv = DictVectorizer(sparse=False)
train_dict = df_train[categorical_columns + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical_columns + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

# train the model
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# get predictions
y_pred = model.predict_proba(X_val)[:, 1]
convert_decision = (y_pred >= 0.5)

# calculate accuracy
accuracy = (y_val == convert_decision).mean()
print(f"Accuracy: {round(accuracy, 2)}")

# Features to exclude
features_to_exclude = ['industry', 'employment_status', 'lead_score']

differences = {}

for feature in features_to_exclude:
    # Exclude the feature
    if feature in categorical_columns:
        excluded_cat = [c for c in categorical_columns if c != feature]
        excluded_features = excluded_cat + numerical
    else:
        excluded_features = categorical_columns + [n for n in numerical if n != feature]
    
    # Train model without the feature
    dv_ex = DictVectorizer(sparse=False)
    train_dict_ex = df_train[excluded_features].to_dict(orient='records')
    X_train_ex = dv_ex.fit_transform(train_dict_ex)
    
    val_dict_ex = df_val[excluded_features].to_dict(orient='records')
    X_val_ex = dv_ex.transform(val_dict_ex)
    
    model_ex = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model_ex.fit(X_train_ex, y_train)
    
    y_pred_ex = model_ex.predict_proba(X_val_ex)[:, 1]
    convert_decision_ex = (y_pred_ex >= 0.5)
    accuracy_ex = (y_val == convert_decision_ex).mean()
    
    diff = accuracy - accuracy_ex
    differences[feature] = diff
    print(f"Accuracy without {feature}: {accuracy_ex}, Difference: {diff}")

Accuracy: 0.7
Accuracy without industry: 0.6996587030716723, Difference: 0.0
Accuracy without employment_status: 0.6962457337883959, Difference: 0.0034129692832763903
Accuracy without lead_score: 0.7064846416382252, Difference: -0.0068259385665528916


### Question 6

- Now let's train a regularized logistic regression.
- Let's try the following values of the parameter `C`: `[0.01, 0.1, 1, 10, 100]`.
- Train models using all the features as in Q4.
- Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these `C` leads to the best accuracy on the validation set?

- 0.01
- 0.1
- 1
- 10
- 100

> **Note**: If there are multiple options, select the smallest `C`.


In [77]:
C_values = [0.01, 0.1, 1, 10, 100]
accuracies = {}

for C in C_values:
    model = LogisticRegression(solver='liblinear', C=C, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    convert_decision = (y_pred >= 0.5)
    accuracy = (y_val == convert_decision).mean()
    accuracies[C] = round(accuracy, 3)
    print(f"C={C}: Accuracy={accuracies[C]}")

C=0.01: Accuracy=0.7
C=0.1: Accuracy=0.7
C=1: Accuracy=0.7
C=10: Accuracy=0.7
C=100: Accuracy=0.7
